dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
dotenv: .env
networks:
  development:
    verify: False
    host: "HTTP://127.0.0.1"
    port: 8545
    network_id: "*"
    chainid: 1337
  ganache:
    verify: False
  goerli:
    host: "https://goerli.infura.io/v3/4108e6964fae4225b9f9c53f461e1cd4"
    port: 443
    network_id: "*"
    chainid: 5
    verify: False
    weth_token: '0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6'
    fau_token: '0xBA62BCfcAaFc6622853cca2BE6Ac7d845BC0f2Dc'
    dai_usd_price_feed: '0x0d79df66BE487753B02D015Fb622DED7f0E9798d'
    eth_usd_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
  sepolia:
    verify: False
    eth_usd_price_feed: '0x694AA1769357215DE4FAC081bf1f309aDC325306'
    chainid: 11155111
    host: "HTTP://127.0.0.1"
    port: 8545
    network_id: "*"
wallets:
  from_key: ${PRIVATE_KEY}
  from_key2: ${PRIVATE_KEY2}
